version: '3.7'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - $HOME/Desktop/influxdb:/var/lib/influxdb
    restart:
      always
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 8080:3000
    volumes:
      - $HOME/Desktop/grafana:/var/lib/grafana
    restart:
      always